
---

- name: Play with GCP resources
  hosts: localhost
  gather_facts: false

  vars:

    gcp:
      project: ansible-eg
      auth_kind: serviceaccount
      service_account_file: "/Users/toran/Downloads/ansible-eg-3583f723f939.json"
      region: "us-west1"
      zone: "us-west1-a"
      scopes:
        - https://www.googleapis.com/auth/compute
      machine_type: "n1-standard-1"

    cloud_run_eg:
      docker_image: ""
      gcs_bucket: "ansible-eg"
      gcs_repo: "myrepo"

    cloud_scheduler:
      scopes:
        - https://www.googleapis.com/auth/cloud-platform

  tasks:
    # make sure the billing account is enabled & linked 
    - name: Enable APIs/Services on the project
      google.cloud.gcp_serviceusage_service:
        state: present
        name: "{{ item }}"
        project: "{{ gcp.project }}"
        auth_kind: "{{ gcp.auth_kind}}"
        service_account_file: "{{ gcp.service_account_file }}"
      loop:
        - compute.googleapis.com
        - run.googleapis.com

    - name: Allocate an IP Address
      gcp_compute_address:
        state: present
        name: 'test-address1'
        region: "{{ gcp.region }}"
        project: "{{ gcp.project }}"
        auth_kind: "{{ gcp.auth_kind }}"
        service_account_file: "{{ gcp.service_account_file }}"
        scopes: "{{ gcp.scopes }}"

    - name: Create Cloud Run Job
      command: >
        gcloud beta run jobs create test-cloudrun-job-2 \
          --image us-docker.pkg.dev/cloudrun/container/job:latest \
          --tasks 50 \
          --set-env-vars SLEEP_MS=10000 \
          --set-env-vars FAIL_RATE=0.5 \
          --max-retries 5 \
          --region {{ gcp.region }}
      register: create_cloudrun_job_res
