---

- name: Play with GCP resources
  hosts: localhost
  gather_facts: false

  vars:

    gcp:
      project: ansible-eg
      auth_kind: serviceaccount
      service_account_file: "/Users/toran/Downloads/ansible-eg-3583f723f939.json"
      region: "us-west1"
      zone: "us-west1-a"
      scopes:
        - https://www.googleapis.com/auth/compute
      machine_type: "n1-standard-1"

    cloud_run_eg:
      docker_image: ""
      gcs_bucket: "ansible-eg"
      gcs_repo: "myrepo"

    cloud_scheduler:
      scopes:
        - https://www.googleapis.com/auth/cloud-platform
  roles:
    - gcp
