- name: My first play
  hosts: mymachinesgroup
  tasks:
      - name: Ping my hosts
        ansible.builtin.ping:
      - name: Print messsage
        ansible.builtin.debug:
            msg: Hello World
