
- name: Get project number
  google.cloud.gcp_resourcemanager_project_info:
    project: "{{ gcp.project }}"
    auth_kind: "{{ gcp.auth_kind}}"
    service_account_file: "{{ gcp.service_account_file }}"
  register: project_number

- name: Echo
  ansible.builtin.debug:
    msg: 
      - "{{ project_number }}"

- name: Enable APIs/Services on the project
  google.cloud.gcp_serviceusage_service:
    state: present
    name: "{{ item }}"
    project: "{{ gcp.project }}"
    auth_kind: "{{ gcp.auth_kind}}"
    service_account_file: "{{ gcp.service_account_file }}"
  loop:
    - compute.googleapis.com
    - run.googleapis.com

- name: Allocate an IP Address
  gcp_compute_address:
    state: present
    name: 'test-address1'
    region: "{{ gcp.region }}"
    project: "{{ gcp.project }}"
    auth_kind: "{{ gcp.auth_kind }}"
    service_account_file: "{{ gcp.service_account_file }}"
    scopes: "{{ gcp.scopes }}"

- name: Create Cloud Run Job
  command: >
    gcloud beta run jobs create test-cloudrun-job-2 \
      --image us-docker.pkg.dev/cloudrun/container/job:latest \
      --tasks 1 \
      --set-env-vars SLEEP_MS=10000 \
      --set-env-vars FAIL_RATE=0.5 \
      --max-retries 1 \
      --region {{ gcp.region }}
  register: create_cloudrun_job_res
